[package]
name = "erikfran-chess-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redkar-chess = { git = "https://github.com/INDA23PlusPlus/redkar-chess" }
#redkar-chess = { git = "https://github.com/ErikFrankling/redkar-chess" }
ggez = "0.9.3"